spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?currentSchema=project_demo_cqrs
    username: user
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: project_demo_cqrs

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082

email:
  sender: demo.project@example.com
  
axon:
  eventhandling:
    processing-mode: tracking
  serializer:
    general: jackson
    events: jackson
    messages: jackson  
  axonserver:
    enabled: false
  saga:
    store-type: jpa